#!/bin/bash
# Runs bootstrapping playbooks against all hosts.

if [ $# -lt 1 ]; then
  echo
  echo "Runs the bootstrap script against all the nodes in the specified group."
  echo "Usage: ./bootstrap ANSIBLE_GROUP"
  exit -1
fi

export ANSIBLE_GROUP="${1}"
export ANSIBLE_HOST_KEY_CHECKING=False

ansible-playbook -u root -i ./linode bootstrap.yml
