#!/bin/bash
# Runs bootstrapping playbooks against all hosts.

if [ $# -lt 1 ]
then
  echo
  echo "Runs the bootstrap script against all the nodes in the specified group."
  echo "Usage: ./bootstrap GROUP"
  exit -1
fi

export BOOTSTRAP_ROLE="${1}"

ansible-playbook -s -u ansibler -i ./linode bootstrap.yml
